# Generated by Django 4.1.3 on 2022-12-09 08:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='^\\d{8,19}$')], verbose_name='Credit Card Number')),
                ('credit_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')], verbose_name='Credit Card CVV')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('charged', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(verbose_name='Subscription Expiry Date')),
                ('credit_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='^\\d{8,19}$')], verbose_name='Credit Card Number')),
                ('credit_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')], verbose_name='Credit Card CVV')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
