# Generated by Django 4.1.3 on 2022-12-10 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('keywords', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('frequency', models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly')])),
                ('end_recurrence', models.DateTimeField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_types', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('keywords', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL)),
                ('class_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='classes.class')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='studios.studio')),
            ],
        ),
    ]
