# Generated by Django 4.1.3 on 2022-12-09 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[a-zA-z0-9]{6}$')])),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('image1', models.ImageField(blank=True, null=True, upload_to='studios', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='studios', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='studios', verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='studios', verbose_name='Image4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='studios', verbose_name='Image5')),
            ],
        ),
        migrations.CreateModel(
            name='StudioAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='studios.studio')),
            ],
        ),
    ]
